# Example DaemonSet deployment for CheckpointBackup controller
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: checkpoint-backup-controller
  namespace: stateful-migration
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: checkpoint-backup-controller
  template:
    metadata:
      labels:
        app.kubernetes.io/name: checkpoint-backup-controller
    spec:
      serviceAccountName: checkpoint-backup-sa
      hostNetwork: true
      containers:
      - name: controller
        image: lehuannhatrang/stateful-migration-operator:checkpointBackup_v2.0
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        # ... other configuration from config/checkpoint-backup/daemonset.yaml
