# Example deployment for MigrationBackup controller
apiVersion: apps/v1
kind: Deployment
metadata:
  name: migration-backup-controller
  namespace: stateful-migration-operator-system
spec:
  replicas: 1
  selector:
    matchLabels:
      control-plane: controller-manager
  template:
    metadata:
      labels:
        control-plane: controller-manager
    spec:
      containers:
      - name: manager
        image: lehuannhatrang/stateful-migration-operator:migrationBackup_v2.6
        command:
        - /manager
        args:
        - --leader-elect
        - --metrics-bind-address=0.0.0.0:8080
        ports:
        - containerPort: 8080
          name: metrics
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 64Mi
