apiVersion: v1
kind: Secret
metadata:
  name: checkpoint-restore-webhook-tls
  namespace: stateful-migration
type: kubernetes.io/tls
data:
  # 아래 두 값은 base64 인코딩! (예: tls.crt -> cat tls.crt | base64 -w0)
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUZNekNDQXh1Z0F3SUJBZ0lVWXdhT0ZWRmFZdDk0NnMvR3ZBZjhaTEs0M3hnd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0ZURVRNQkVHQTFVRUF3d0tkMlZpYUc5dmF5MWpZVEFlRncweU5UQTVNamt4TVRVMk16TmFGdzB6TlRBNQpNamN4TVRVMk16TmFNRUF4UGpBOEJnTlZCQU1NTldOb1pXTnJjRzlwYm5RdGNtVnpkRzl5WlMxM1pXSm9iMjlyCkxYTjJZeTV6ZEdGMFpXWjFiQzF0YVdkeVlYUnBiMjR1YzNaak1JSUJJakFOQmdrcWhraUc5dzBCQVFFRkFBT0MKQVE4QU1JSUJDZ0tDQVFFQXQ1V1NweVRMVWQrOXRIQUF4a3V5WVp1enNNa2c5NFVpZnlmNU41SGNXTjRmbnNScgpxN21BUUZ2Zi8rQkxkamlLZGlCc2t4aWp5b0U5RjVVTHFlc2dvZmhtSkNVdStSN2J5TlZ1OUViV2loYWdvRVdRCi8xRnBZTjZwSzlYbFRYRXlabWEwQmVJcGIyNU1qN1k2eFBLMmVSOGRmS0U4WGowczNkZmRUNDhWSEUyaWo0eUIKUmYxcFpGbEV6aG00TkRiVEM5TlJTdmNvMjNneFZKRDdEQnprNm5sUU9sajZaZFN5NnJNZVpadE5TWDZnZ3k0NQpobXgrSjhxNWVBYkJlakVuWFBKS0NMblV4bk1DTlQwVGh0dC9zWWcwaGlraHUwWlE1eUxqVkdVSzFHekRBam90Ck9scWNCeFFPcTd3MkE3R3R2ajJrOHZUT216d25MRFVFbVpXV3BRSURBUUFCbzRJQlRqQ0NBVW93SHdZRFZSMGoKQkJnd0ZvQVViWjNSandnNnNRQ0xXRTBGRWJnV0RPSEhtcU13Q1FZRFZSMFRCQUl3QURBTEJnTlZIUThFQkFNQwpCYUF3RXdZRFZSMGxCQXd3Q2dZSUt3WUJCUVVIQXdFd2dkb0dBMVVkRVFTQjBqQ0J6NEllWTJobFkydHdiMmx1CmRDMXlaWE4wYjNKbExYZGxZbWh2YjJzdGMzWmpnakZqYUdWamEzQnZhVzUwTFhKbGMzUnZjbVV0ZDJWaWFHOXYKYXkxemRtTXVjM1JoZEdWbWRXd3RiV2xuY21GMGFXOXVnalZqYUdWamEzQnZhVzUwTFhKbGMzUnZjbVV0ZDJWaQphRzl2YXkxemRtTXVjM1JoZEdWbWRXd3RiV2xuY21GMGFXOXVMbk4yWTRKRFkyaGxZMnR3YjJsdWRDMXlaWE4wCmIzSmxMWGRsWW1odmIyc3RjM1pqTG5OMFlYUmxablZzTFcxcFozSmhkR2x2Ymk1emRtTXVZMngxYzNSbGNpNXMKYjJOaGJEQWRCZ05WSFE0RUZnUVVqVVVHYUVscFRIaHN1cVdMYWJxeDJpQUpWMUF3RFFZSktvWklodmNOQVFFTApCUUFEZ2dJQkFGVDZMTU5uWDhrWWF4TnVpakQ5aWZMZ0YyWjdFOFZrczBycjlBd2F4aUhxZjVWOFQybVE1YUtyCjJXSEdzeTZZN25QZnNaSzdyRFpWczR6K1VMRTNOdGxRSFlCMFovQzJ6YTQ5ZjZ6bFB6SGt1MkE4eEx1K0dvNWQKSiszZXhFNmFuV0xuVDNhUjJpaktxcHBHZ1ByeVZHUDIwd3ZDUkhzanMzOHc0cENTUHJzWHZDalJqNENjR3g1SQp1a2JzRjJDbjV2bjVVWm1FckRCWW1yWmllZnArZGxLUW8xaTNUc1pCajRDa0pxNk1RcXd4TlpRSERYaHBkWUVtCjkzazkzZlI1N0hRL1QyR3BWT05RVlNSVVBYd1dvUlpHMy9xZm9lSEprZFc3Y1U3STRZNGtpTENVeTdueS9BMkoKeVB0S1ZCYlhDUkR3dnBtQmpMZFFxZ0xCT3M0bXoxYUxGRlBhcnBMOG51bmZZeXcvY1NRamRXYkhwYW9qcDY4LwpCRk5qb0pPVDI3MG9xbUFqM2dvd0Z2dDhUN0hqT0xtOFZaRVNjVnRhZGt6cDhGSHdjL1F2UzYwMll1OTVZbk9VCnk0Z2U1M3NZT0RkR2k5RjQzYWI4c2ZVM2F6aU1pTVg0T1Qza0FMTStIdXRWSVd6TTI0UktNRktjY0RVMGtCb1kKUGhNbmN6WHZvVVl2SlgyQ2lxcWlNU3lXMyt2NFhLS1ZVeVk1SldMdVZFdE1YYmJSS2c1OExwRlNqUU5jTzhDTAoxOXpwS1V6elV5b2tqY1JkQXNkYXdGVTZnbXFyZEtMcGVZblV1YlhXQkxNdk5lbzk2ZjNyell4d3BKN1pxUWZmCll3cDRXeTBkaUJ4QVRjekZ1R1BnMmdIZTlGWEw4TEcvQU02NkwySFl3T0ljK3JpL2JZUnUKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
  tls.key: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2UUlCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktjd2dnU2pBZ0VBQW9JQkFRQzNsWktuSk10UjM3MjAKY0FER1M3SmhtN093eVNEM2hTSi9KL2sza2R4WTNoK2V4R3VydVlCQVc5Ly80RXQyT0lwMklHeVRHS1BLZ1QwWApsUXVwNnlDaCtHWWtKUzc1SHR2STFXNzBSdGFLRnFDZ1JaRC9VV2xnM3FrcjFlVk5jVEptWnJRRjRpbHZia3lQCnRqckU4clo1SHgxOG9UeGVQU3pkMTkxUGp4VWNUYUtQaklGRi9XbGtXVVRPR2JnME50TUwwMUZLOXlqYmVERlUKa1BzTUhPVHFlVkE2V1BwbDFMTHFzeDVsbTAxSmZxQ0RMam1HYkg0bnlybDRCc0Y2TVNkYzhrb0l1ZFRHY3dJMQpQUk9HMjMreGlEU0dLU0c3UmxEbkl1TlVaUXJVYk1NQ09pMDZXcHdIRkE2cnZEWURzYTIrUGFUeTlNNmJQQ2NzCk5RU1psWmFsQWdNQkFBRUNnZ0VBQnpUV245RGNyMVIrL3FCLzZKNGc1NGtrWXdNK0tVdmZXRitpRTRtYVVwMjQKM3Q0RjA2VHhrUi9hSkR5ZEp3dnpUczJaTXRGVDMvZUxSYUZLNXRXMzZmWnEwZ1BvcGJiNFRkaFNVRUgxOENVNwp2Y0dGVTlSbkNjK3J2ZHRhQjl4eWxwejA5NThvQjd1c0dJbkF6RlF5WlZaRjdYWVVmU2JkeGtFNmxZSFZHYm9zCk0xQVB6SThZTDAvQ1pLZFFCM1Z5Wi8rY2dSeENBR29Xa0tpVndQU1VHUVE1anZwVHFkTmlyL0FnN3A3aFBhRE0KeHdNNmRTZ3ljbXk1eTdtQ1VDTTIvQ2p6bWVVS2R0d283cm9OdTFMbng5ZTVHczYwa01qL0oyL2c4ck9hWTRTRgpnR1JabjFCY0JQcFNFZHZHU0lpUk04aDdPNklPZGlUWXVxMXNhb0hZYVFLQmdRQzR1WEdmbGw2Q2t2MnNKZXdHCjlKMXQ2NWp5WnFKUzlwV1FDWVZxUTdDMmhCbTRidUN2NFRxS05MZjBpTU1Wd1ZtR2VPWjJ1VUpqZ1lMbmJjWnEKTnIveDhmcFM3RFZWV29DbCsxTXV0Q3Z5UG1lbTFxVHZ5aUlFMjhkbEFobkxaYkYvdCtsNk5lOWVYL3B1RmMraApVd3dLc0trN0p1SkxRQTAyeFNjbXdaZHZiUUtCZ1FEK2E0TFZuZG9lbUQ1K2I2dEQ1R1ErcVg1Qy9YK0YyR2VCCkJNOEoyOVhxSUVDak9nZVNtMUduNE9GY2xxSXVBdHEzN0t6ZDhCWHZPKzErRHN4cVRpRHFnK1RrS1YxK3hzTk4KMFJTUU1XR3U1Tk9GVEgwaVdEWlc1Y3dOT2tnbmFkMUpEYytRNElPTi9hUUdqTVNmRXlrN3NWYjY5SjU3ZVpIaAowRU52Z25ocEdRS0JnRi9rZkpSd3RjMG95eURqYXJ4Tm5hL2pIcm12QjlMemlMNkdBc2tnTElzQzFtdEV1OFR4CnNiYnZHUk9MTDJLS3haT21EVlZTWktGTktReEVrenl1QVVSeTdoUy81QXZUK0hheG1nUGpxZkNON3JiUU5EejYKZkdCelN2WW5lZ1o1V3dSSEQ1L09nZDFIQzdTOEE5WG1TNWo5RGt6VHFhT1FzNHRjR3kvbVRWdWRBb0dCQU1Qawp5ZmRxdEZDTVRzb1JkMkF1RWRXQnNkc296ckNqQUljQnlkeEFiVVA1RTJ2YXVZdnpsWHJhbHdzd1hLMXF1emVVCnYwR2ZvM1B4dzVvbEVOWGxWRWpkeHphNmR1ZXZhUitZbGVtMGJBODYxM2F5ZjBNYmdyT0Qrb3BRenMreUhwVXEKVWlDdURmMGRSOWRYT2VsMTJuREF5a1V1Wm55U0RYWStZajRReWwrNUFvR0FhbUkyT2NYRWhCTFR1eVptNG1YRQpSdzF0OGprck01QjJnWjNDdEJHcEZSZWRGc1RYRlN5MVJWS3FlNlVDbzZEUVpqdnhiRDVhNFJvNmtmdGNuZ1V1CkgzMnpwNkR1Y1g1UThuUCs0WkNBTWIxVXVvNFNRYXk3YWhOaUcxU1ZQOEZUcW5nMEVPMkE4b0Rzb2pEdlpmbVgKK3lLMEs4NEI5MUNUUHRTWFN6MHpqc2c9Ci0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0K
---
apiVersion: v1
kind: Service
metadata:
  name: checkpoint-restore-webhook-svc
  namespace: stateful-migration
spec:
  selector:
    app: checkpoint-restore-webhook
  ports:
    - name: https
      port: 443
      targetPort: 8443
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: checkpoint-restore-webhook
  namespace: stateful-migration
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: checkpoint-restore-webhook
  namespace: stateful-migration
spec:
  replicas: 1
  selector:
    matchLabels: { app: checkpoint-restore-webhook }
  template:
    metadata:
      labels: { app: checkpoint-restore-webhook }
    spec:
      serviceAccountName: checkpoint-restore-webhook
      containers:
      - name: webhook
        image: jeongseungjun/webhook-server:v2.1
        ports: [{ containerPort: 8443 }]
        env:
        - name: CHECKPOINT_RESTORE_GVR_GROUP
          value: migration.dcnlab.com   # 실제 그룹으로!
        - name: CHECKPOINT_RESTORE_GVR_VERSION
          value: v1
        - name: CHECKPOINT_RESTORE_GVR_RESOURCE
          value: checkpointrestores
        volumeMounts:
        - name: tls
          mountPath: /tls
          readOnly: true
        readinessProbe:
          httpGet: { scheme: HTTPS, path: /readyz, port: 8443 }
        livenessProbe:
          httpGet: { scheme: HTTPS, path: /healthz, port: 8443 }
      volumes:
      - name: tls
        secret:
          secretName: checkpoint-restore-webhook-tls