apiVersion: migration.dcnlab.com/v1
kind: CheckpointBackup
metadata:
  name: example-stop-pod-checkpoint
  namespace: default
spec:
  # Use "immediately" for one-time checkpoint
  schedule: "immediately"
  
  # Set to true to delete pod after checkpointing
  stopPod: true
  
  podRef:
    name: example-pod
    namespace: default
  
  resourceRef:
    apiVersion: apps/v1
    kind: Deployment
    name: example-deployment
    namespace: default
  
  registry:
    url: "docker.io"
    repository: "myrepo/checkpoints"
    secretRef:
      name: registry-credentials
      namespace: default
  
  containers:
  - name: app-container
    image: "myrepo/checkpoints:example-pod-app-container-checkpoint"
